//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionViolation
    {
        public int Id { get; set; }
        public int InspectionId { get; set; }
        public int ViolationId { get; set; }
    
        public virtual Inspection Inspection { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
